name = "fileshare"
compatibility_date = "2024-09-23"
pages_build_output_dir = "public"

[vars]
TURSO_ORG = "ishman"
TURSO_REGION = "aws-us-east-2"
TURSO_NODES = "3"
TURSO_TOKEN = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJnaWQiOiI4OTFlNjlhNy01MGYwLTRmOGEtYWY5OS01ZjEzZWVmOTQ1OTIiLCJpYXQiOjE3NzMxMTA3MTgsInJpZCI6IjA4YmVmYWJjLTMyYjMtNGY4OC1hNGFmLWQyOTA1NjExMzI2NyJ9.JCJMHAooSXfK-t7Gu8mbwnfqQ_AmX-wWRCqssBRHWKz5b_0NlUUhb_e_V-VZAAVR7K9q00w6oVBvSKQx30hQBw"
TURSO_AUTH_URL = "libsql://fileshareauth-ishman.aws-us-east-2.turso.io"
TURSO_AUTH_TOKEN = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJnaWQiOiI0MzZhNjU3OC0xMzc0LTQ0NmMtOTI3OS1lNzIwMDQ4ZDJhOWMiLCJpYXQiOjE3NzMxMTA3MzgsInJpZCI6IjQ3MzQ4YzA3LWVkMTItNDhhZi04ZDdkLTIzYmI2NjY0MzBmMCJ9.44BPkH0Wkz8icFlvhsOrymzOiWw_aZIOsdsQRgcN6fhlovjD-QO2Gos2tImpmM3s57vOY57RtE23WX9QkeGQBw"
