name = "fileshare"
compatibility_date = "2024-09-23"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "fileshare-db"
database_id = "9fd8b376-3d3b-4bc0-a2cd-bf0ad1868541"
