CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  access_code TEXT NOT NULL, -- SHA-256 hashed
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
